version: "3.8"
services:
  app:
    build: ./docker/php
    volumes:
      - ./laravel:/laravel
      - vendor-store:/laravel/vendor
      - node_modules-store:/laravel/node_modules

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./laravel:/laravel
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - node_modules-store:/laravel/node_modules
    working_dir: /

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
    db-store:
    vendor-store:
    node_modules-store:
