version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
         key: composer-v1-{{ checksum "./laravel/composer.lock" }}
      - run:
          working_directory: laravel
          command: composer install -n --prefer-dist
      - save_cache:
         key: composer-v1-{{ checksum "./laravel/composer.lock" }}
         paths:
          - ./laravel/vendor
      - restore_cache:
         key: npm-v1-{{ checksum "./laravel/package-lock.json" }}
      - run:
         working_directory: laravel
         name: npm install
         command: |
           if [ ! -d ./laravel/node_modules ]; then
             npm install
           fi
      - save_cache:
         key: npm-v1-{{ checksum "./laravel/package-lock.json" }}
         paths:
           - node_modules
      - run:
          working_directory: laravel
          command: npm run dev
      - run:
          name: php test
          working_directory: laravel
          command: vendor/bin/phpunit
