<?php

use Illuminate\Database\Seeder;
use App\Models\Book;
use Illuminate\Support\Facades\DB;

class BooksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // ファクトリー作成
        // factory(Book::class, 50)->create();

        DB::table('books')->insert([
        //    [
        //         'title' => '',
        //         'img_url' => '',
        //         'author' => '',
        //         'isbn' => '',
        //         'page' => '',
        //         'publisher' => '',
        //         'published_at' => '',
        //         'description' => '',
        //         'read_at' => null,
        //         'user_id' => 1,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //    ],
        [
        'title' => '嫌われる勇気―――自己啓発の源流「アドラー」の教え',
        'img_url' => 'https://book-quote.s3-ap-northeast-1.amazonaws.com/book-cover/kirawareruyuuki.jpeg',
        'author' => '岸見 一郎',
        'isbn' => '9784478025819',
        'page' => 294,
        'publisher' => 'ダイヤモンド社',
        'published_at' => '2013/12/12',
        'description' => '本書は、フロイト、ユングと並び「心理学の三大巨頭」と称される、アルフレッド・アドラーの思想(アドラー心理学)を、「青年と哲人の対話篇」という物語形式を用いてまとめた一冊です。欧米で絶大な支持を誇るアドラー心理学は、「どうすれば人は幸せに生きることができるか」という哲学的な問いに、きわめてシンプルかつ具体的な“答え”を提示します。この世界のひとつの真理とも言うべき、アドラーの思想を知って、あなたのこれからの人生はどう変わるのか?もしくは、なにも変わらないのか…。さあ、青年と共に「扉」の先へと進みましょう―。',
        'read_at' => null,
        'user_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
        ],
        [
        'title' => '反応しない練習: あらゆる悩みが消えていくブッダの超・合理的な「考え方」',
        'img_url' => 'https://book-quote.s3-ap-northeast-1.amazonaws.com/book-cover/hannnousinairennsyuu.jpeg',
        'author' => '草薙龍瞬',
        'isbn' => '9784041030400',
        'page' => '222',
        'publisher' => 'KADOKAWA',
        'published_at' => '2015',
        'description' => '悩みは「消す」ことができる。そしてそれには「方法」がある――ブッダの「超合理的で、超シンプル」な教えを日常生活に活かすには? 注目の“独立派”出家僧が原始仏教からひもとく“役に立つ仏教”。',
        'read_at' => null,
        'user_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
       ],
       [
        'title' => 'ゼロ秒思考: 頭がよくなる世界一シンプルなトレーニング',
        'img_url' => 'https://book-quote.s3-ap-northeast-1.amazonaws.com/book-cover/zerobyousikou.jpeg',
        'author' => '赤羽雄二',
        'isbn' => '9784478020999',
        'page' => '214',
        'publisher' => 'ダイヤモンド社',
        'published_at' => '2013',
        'description' => 'A4の紙に1件1ページで書く。ゆっくり時間をかけるのではなく、1ページを1分以内にさっと書く。毎日10ページ書き、フォルダに投げ込んで瞬時に整理する。それだけで、マッキンゼーのプログラムでも十分に教えていない、最も基本的な「考える力」を鍛えられる。深く考えることができるだけでなく、「ゼロ秒思考」と言える究極のレベルに近づける。',
        'read_at' => null,
        'user_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
   ],
    [
        'title' => 'チーズはどこへ消えた？',
        'img_url' => 'https://book-quote.s3-ap-northeast-1.amazonaws.com/book-cover/tiizuhadokonikieta.jpeg',
        'author' => 'スペンサー・ジョンソン',
        'isbn' => '',
        'page' => '96',
        'publisher' => '扶桑社',
        'published_at' => '2000/11/30',
        'description' => 'この小さな本が世界のビジネスマンを変えてゆく!迷路のなかに住む、2匹のネズミと2人の小人。彼らは迷路をさまよった末、チーズを発見する。チーズは、ただの食べ物ではなく、人生において私たちが追い求めるもののシンボルである。ところがある日、そのチーズが消えた!ネズミたちは、本能のままにすぐさま新しいチーズを探しに飛び出していく。ところが小人たちは、チーズが戻って来るかも知れないと無駄な期待をかけ、現状分析にうつつを抜かすばかり。しかし、やがて一人が新しいチーズを探しに旅立つ決心を…。大手トップ企業が次々と社員教育に採用。単純なストーリーに託して、状況の変化にいかに対応すべきかを説き、各国でベストセラーとなった注目の書。状況変化への対応を説いたビジネス書として、人生のいろいろな局面を象徴した生き方の本として多くの人に読まれています。アナタの人生は確実に変わる!',
        'read_at' => null,
        'user_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => '時間革命: 1秒もムダに生きるな',
        'img_url' => 'https://book-quote.s3-ap-northeast-1.amazonaws.com/book-cover/jikannkakumei.jpeg',
        'author' => '堀江貴文',
        'isbn' => '9784023318304',
        'page' => '235',
        'publisher' => '朝日新聞出版',
        'published_at' => '2019',
        'description' => 'あなたの人生に「革命」を起こす!ホリエ式時間術。',
        'read_at' => null,
        'user_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'PHPﾌﾚｰﾑﾜｰｸLaravel入門第2版',
        'img_url' => 'https://book-quote.s3-ap-northeast-1.amazonaws.com/book-cover/laravel_1.jpeg',
        'author' => '掌田津耶乃',
        'isbn' => '9784798060996',
        'page' => '356',
        'publisher' => '秀和システム',
        'published_at' => '2020',
        'description' => '2017年刊行後大好評の『PHPフレームワークLaravel入門』が2019年9月リリースのバージョン6に対応した改訂版!',
        'read_at' => null,
        'user_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'PHPフレームワーク Laravel Webアプリケーション開発バージョン5.5LTS対応',
        'img_url' => 'https://book-quote.s3-ap-northeast-1.amazonaws.com/book-cover/laravel_2.jpeg',
        'author' => '竹澤有貴, 栗生和明, 新原雅司, 大村創太郎',
        'isbn' => '9784802611848',
        'page' => '531',
        'publisher' => 'ソシム',
        'published_at' => '2018/10/05',
        'description' => '“実践パターン”と“ユースケース”で学ぶ、開発現場で使えるプロのテクニック。Laravelアプリケーションの構造・設計がすべて分かる。データベースとの連携、ユーザー認証、処理の分離、テスト駆動開発、運用etc.',
        'read_at' => null,
        'user_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'HTML5/CSS3モダンコーディング フロントエンドエンジニアが教える3つの本格レイアウト スタンダード・グリッド・シングルページレイアウトの作り方',
        'img_url' => 'https://book-quote.s3-ap-northeast-1.amazonaws.com/book-cover/htmlcss.jpeg',
        'author' => '吉田 真麻',
        'isbn' => '9784798141572',
        'page' => '256',
        'publisher' => '翔泳社',
        'published_at' => '2015/11/02',
        'description' => 'フロントエンドエンジニアから学ぶ制作現場の実践的なテクニック!本書は、HTML5/CSS3を使ってモダンなサイトを制作するためのコーディングテクニックをハンズオン形式で学ぶ書籍です。現在主流なWebページのデザインスタイル、「スタンダードレイアウト」「グリッドレイアウト」「シングルページレイアウト」を適用した3つのサイトを作りながら、各スタイルの特徴や使い分け、コーディングテクニックを学びます。実際のWeb 制作の現場と同様に、サイトのデザインを基にして骨格を見極め、枠組みから中身までひと通りコーディングするというフローをなぞることで、HTML5/CSS3の実用的なコーディングスキルやテクニックを無理なく身につけることができます。3つのサイトを作成することで、「本格的なレイアウトのサイトを作れた」「こういったレイアウトの場合こうコーディングすればいいという具体的なテクニックがわかった」というような手応えを得やすく、学ぶことへのモチベーションが下がらずに高まる構成にしています。駆け出しのフロントエンドエンジニアや、HTML/CSSコーディングに興味はあっても実践の機会がないデザイナー、バックエンドエンジニアなどが、実際にサイトを作ることを通してスキルアップすることを目標とした一冊です。※本電子書籍は同名出版物を底本として作成しました。記載内容は印刷出版当時のものです。※印刷出版再現のため電子書籍としては不要な情報を含んでいる場合があります。※印刷出版とは異なる表記・表現の場合があります。予めご了承ください。※プレビューにてお手持ちの電子端末での表示状態をご確認の上、商品をお買い求めください。',
        'read_at' => null,
        'user_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => '入門『地頭力を鍛える』　３２のキーワードで学ぶ思考法',
        'img_url' => 'https://book-quote.s3-ap-northeast-1.amazonaws.com/book-cover/jiatama32.jpeg',
        'author' => '細谷　功',
        'isbn' => '9784492557884',
        'page' => '229',
        'publisher' => '東洋経済新報社',
        'published_at' => '2019/07/26',
        'description' => '戦略的思考、ロジカルシンキング、地頭力、具体と抽象、無知の知…32のキーワードの「WHAT(何?)」「WHY(なぜ?)」「HOW(どう使う?)」がすっきりわかる。 --このテキストは、tankobon_hardcover版に関連付けられています。',
        'read_at' => null,
        'user_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => '本当の自由を手に入れるお金の大学',
        'img_url' => 'https://book-quote.s3-ap-northeast-1.amazonaws.com/book-cover/okanenodaigaku.jpeg',
        'author' => '両＠リベ大学長',
        'isbn' => '9784023318786',
        'page' => '272',
        'publisher' => '株式会社朝日新聞出版',
        'published_at' => '2020/06/19',
        'description' => '日本一わかりやすいお金の教養チャンネル「リベ大」の誰も言わないけど、やれば人生が変わる〈お金の勉強〉超実践型バイブル!　経済的な不安がなくなり、貯める・稼ぐ・増やす・守る・使う、一生お金に困らない「5つの力」が身につく！',
        'read_at' => null,
        'user_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => '「言葉にできる」は武器になる。',
        'img_url' => 'https://book-quote.s3-ap-northeast-1.amazonaws.com/book-cover/kotobanidekiruhabukininaru.jpeg',
        'author' => '梅田悟司',
        'isbn' => '9784532320751',
        'page' => '256',
        'publisher' => '日経BP',
        'published_at' => '2016/08/25',
        'description' => '人を動かすために「心地いい言葉」はいらない！　自分の思いをどうやって「言葉」にして「伝える」か?　人の心を動かす「表現」には秘密があるのか?　「うまく自分の言葉で話せない」「人の心に刺さる表現力を身につけたい」――志や思い、自分のなかにあるビジョンを言語化するために何をすればよいのか?　そんな悩みを抱えている全ての人に、いま注目のコピーライターが独自の手法をわかりやすく開示する、人の心を動かす言葉の法則。人は、その言葉の中に自分の思いを発見したときに心を動かされるのであり、技巧を凝らした表現などいらない。自身が手がけた広告コピー、古今東西の有名事例を、「メッセージとしての明確性」「そこにいかに自分を投影するか」「伝えたい想いをいかに生み出すか」という視点から分解、「意志を言葉に込める技術」を解説する。',
        'read_at' => null,
        'user_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => '新しいLinuxの教科書',
        'img_url' => 'https://book-quote.s3-ap-northeast-1.amazonaws.com/book-cover/linuxnokyoukasyo.jpeg',
        'author' => '三宅英明, 大角祐介',
        'isbn' => '9784797380941',
        'page' => '425',
        'publisher' => 'Sbクリエイティブ',
        'published_at' => '2015',
        'description' => 'MS‐DOSを知らない世代のエンジニアに向けたLinux入門書の決定版。Linux自身の機能だけでなく、シェルスクリプトを使ったプログラミングや、Gitによるソフトウェア開発のバージョン管理など、イマドキのエンジニアなら知っておくべき知識についても、丁寧に解説しました!Redhat系、Debian系に対応。',
        'read_at' => null,
        'user_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Amazon Web Services 基礎からのネットワーク＆サーバー構築　改訂3版',
        'img_url' => 'https://book-quote.s3-ap-northeast-1.amazonaws.com/book-cover/aws.jpeg',
        'author' => '大澤文孝, 玉川憲, 片山暁雄, 今井雄太',
        'isbn' => '',
        'page' => '216',
        'publisher' => '日経BP',
        'published_at' => '2020/02/07',
        'description' => '「自分でネットワークやサーバーを構築できるようになる」。これが本書の目的です。新しいものを学習するとき、実際にやってみるのが一番。従来は物理機器がないと学べませんでしたが、今はクラウドがあります。本書は、代表的なクラウドサービス「Amazon Web Services」を実機代わりにネットワークを学び直す、をコンセプトにまとめた1冊です。インフラを学びたい若手技術者にも、インフラを学び直したいアプリ開発者にもオススメです。',
        'read_at' => null,
        'user_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    // [
    //     'title' => '',
    //     'img_url' => '',
    //     'author' => '',
    //     'isbn' => '',
    //     'page' => '',
    //     'publisher' => '',
    //     'published_at' => '',
    //     'description' => '',
    //     'read_at' => null,
    //     'user_id' => 1,
    //     'created_at' => now(),
    //     'updated_at' => now(),
    // ],

        ]);
    }
}
